'use client';

import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { ConfidenceBadge } from './confidence-badge';
import { WarningsList } from './warnings-list';
import { RoutingCTA } from './routing-cta';
import { RegenerateButton } from './regenerate-button';
import { ResultsEmailCapture } from './results-email-capture';
import { Card, CardContent } from '@/components/ui/card';
import { ChevronDown, Cog, FileText } from 'lucide-react';
import type { AssessmentResult, Report } from '@/engine/types';

interface ReportDisplayProps {
  assessment: AssessmentResult;
  initialReport: Report;
}

export function ReportDisplay({ assessment, initialReport }: ReportDisplayProps) {
  const [markdown, setMarkdown] = useState(initialReport.markdown);
  const [methodologyOpen, setMethodologyOpen] = useState(false);

  return (
    <div className="space-y-8">
      {/* Meta: confidence + regenerate */}
      <div className="flex items-center justify-between">
        <ConfidenceBadge confidence={assessment.confidence} />
        <RegenerateButton
          sessionId={assessment.sessionId}
          onRegenerated={(md) => setMarkdown(md)}
        />
      </div>

      {/* Structural warnings (from rules engine) — always shown */}
      <WarningsList warnings={assessment.warnings} />

      {/* LLM-generated report prose */}
      <Card variant="elevated">
        <CardContent className="pt-6">
          <div className="prose prose-gray max-w-none prose-headings:font-semibold prose-headings:text-[#1a1f36] prose-h2:text-lg prose-p:text-[#4a5568] prose-li:text-[#4a5568] prose-strong:text-[#1a1f36] prose-a:text-[#00C9A7] prose-a:no-underline hover:prose-a:underline">
            <ReactMarkdown>{markdown}</ReactMarkdown>
          </div>
        </CardContent>
      </Card>

      {/* Routing CTAs — driven by engine routing tags */}
      <div className="border-t border-gray-200 pt-8">
        <h2 className="mb-4 text-base font-semibold text-[#1a1f36]">Your next steps</h2>
        <RoutingCTA routingTags={assessment.routingTags} />
      </div>

      {/* About this assessment — methodology */}
      <div className="border-t border-gray-200 pt-6">
        <button
          type="button"
          onClick={() => setMethodologyOpen((v) => !v)}
          className="flex w-full items-center justify-between text-sm font-medium text-gray-500 hover:text-[#1a1f36] transition-colors"
        >
          <span className="flex items-center gap-2">
            <Cog className="h-4 w-4" />
            About this assessment
          </span>
          <ChevronDown
            className={`h-4 w-4 transition-transform ${methodologyOpen ? 'rotate-180' : ''}`}
          />
        </button>
        {methodologyOpen && (
          <div className="mt-4 rounded-lg bg-gray-50 border border-gray-200 p-5 text-sm text-[#4a5568] space-y-3">
            <div className="flex items-start gap-3">
              <Cog className="h-4 w-4 text-[#00C9A7] mt-0.5 shrink-0" />
              <p>
                <strong className="text-[#1a1f36]">Rules engine:</strong> Your answers were
                processed by a deterministic rules engine that applies federal student loan policy
                criteria. The same inputs always produce the same results.
              </p>
            </div>
            <div className="flex items-start gap-3">
              <FileText className="h-4 w-4 text-[#00C9A7] mt-0.5 shrink-0" />
              <p>
                <strong className="text-[#1a1f36]">AI formatting:</strong> The report text was
                generated by an AI model that only has access to the engine&apos;s pre-computed
                output — not your raw inputs and not external policy information. This prevents the
                AI from inventing policy details.
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Sticky email capture — appears after scrolling 60% */}
      <ResultsEmailCapture
        sessionId={assessment.sessionId}
        routingTags={assessment.routingTags}
      />
    </div>
  );
}
